### ISSUE TITLE
Not working using cuda

### ISSUE THREAD

**Issue by Fable67** [lessw2020/Ranger-Deep-Learning-Optimizer#1]
Variables self.slow_weights are always on cpu.
You can easily fix this by adding a .to() method in Ranger class like so:

    def to(self, device):    
        if device is "cuda":
            for i in range(len(self.slow_weights)):
                for j, w in enumerate(self.slow_weights[i]):
                    self.slow_weights[i][j] = w.cuda()
        elif device is "cpu":
            for i in range(len(self.slow_weights)):
                for j, w in enumerate(self.slow_weights[i]):
                    self.slow_weights[i][j] = w.cpu()

**Comment by pabloppp** [comment]
Are you by any chance creating your Ranger optimizer **before** moving your model to CUDA?

If so, what you're experiencing is a know error on optimizers that imitialize internal state based on the model parameters, like Adagrad, and would be solved just by instantiating your optimizer **after** you move your model to CUDA.

Here's a post where they mention this issue: https://discuss.pytorch.org/t/effect-of-calling-model-cuda-after-constructing-an-optimizer/15165/7

It's not so common moving the optimizer parameters to cpu/cuda after instantiating them, so I think adding a 'to' method to the optimizer with that purpose, as you suggest, would not be very familiar to regular PyTorch users.

**Comment by lessw2020** [comment]
Thanks everyone for the feedback on both sides here.
@pabloppp is correct, that PyTorch expects the optimizer to be instantiated after the model is created.
That ordering ensures the correct GPU handling.
