### ISSUE TITLE
AttributeError: 'Ranger' object has no attribute 'radam_buffer'

### ISSUE THREAD

**Issue by kayuksel** [lessw2020/Ranger-Deep-Learning-Optimizer#11]
Getting the following error from the most recent version:

AttributeError: 'Ranger' object has no attribute 'radam_buffer'

**Comment by nicocheh** [comment]
How did you solve it @kayuksel ?

**Comment by JSpenced** [comment]
I get this on trying to load in the state dict on a retry and it returns a key error so also curious how you fixed that.
