### ISSUE TITLE
How to cite Ranger in a paper?

### ISSUE THREAD

**Issue by askerlee** [lessw2020/Ranger-Deep-Learning-Optimizer#16]
In my recent paper I used Ranger. I wish to give all the credit the author(s) deserves, but I'm not sure how to properly cite it? Currently I cited the medium article. Should I cite this github repo instead? Thanks.

**Comment by lessw2020** [comment]
Hi @askerlee,
Very cool, thanks using Ranger and citing it!  
Either way is fine - I plan to keep both in sync, so if you have already cited the medium article just run with that. 
If you can post a link to your paper once public that would be great to see :)
Thanks again,
Less

**Comment by askerlee** [comment]
It's a little workshop paper, now on arxiv: https://arxiv.org/abs/1910.08721

**Comment by askerlee** [comment]
Also thank you for your implementation of Mish. I actually used Mish in this work yesterday and found it improved the results further. I would update this paper accordingly in a newer version :D

**Comment by lessw2020** [comment]
Hi @askerlee,
Congrats on the paper - I read through it, very nice work and concept.  And - thanks a bunch for the Ranger mention (first Arxiv paper reference for Ranger!). 
Also great to hear Mish was helpful! 
Good luck with continued work on EddyNet.  I have some additional tweaks for Ranger and RangerQH in the future as I can get time to work on it more, so hopefully it may offer future improvements for you, and thanks again for the citation!
Best regards,
Less

**Comment by askerlee** [comment]
@lessw2020 Thank you for your nice words! Can't wait to try improved ranger 😄 BTW is RangerQH an enhanced version of Ranger?

**Comment by neuronflow** [comment]
could you provide a BibTex please?
