### ISSUE TITLE
Making it a python package

### ISSUE THREAD

**Issue by mpariente** [lessw2020/Ranger-Deep-Learning-Optimizer#20]
Would you like to make this a python package that could be installed with pip? It would be more practical.

I'd like to include it in my repo [asteroid](https://github.com/mpariente/AsSteroid) and give you proper credit for it. 

One way is to install a python package (I can make a PR for that), the other one would be to copy-paste some of the code and point to the license file. Which way would you prefer?

**Comment by pabloppp** [comment]
Not sure if it fits your needs but I added it to my repo https://github.com/pabloppp/pytorch-tools that you can install using pip (the instructions are in the readme) and I try to keep it up to date with the original implementation.
Of course, I creade my repo mainly for personal use so I have other tools that I personally find interesting, so you might be adding things that you don't need to your project.

**Comment by mpariente** [comment]
Thanks for the suggestion, I'll look into it

**Comment by lessw2020** [comment]
Hi @mpariente,
Thanks for the idea and sorry for the delay in my reply.
Yes, it would be great to make it a proper python package for pip install.
I think the better way would be to do the PR to install a python package.
I'm not familiar with that process but if you can help on that front that would be great.
I have plans to try and integrate Ranger regular and RangerQH into one optimizer where the user can toggle with a param which mode to run in and that would make it easy for people to test both Rangers for their specific dataset.
Thanks!

**Comment by mpariente** [comment]
Looking forward to this optimizer, thank you for your work and thanks for merging the PR.
