### ISSUE TITLE
Is there a publication of Ranger?

### ISSUE THREAD

**Issue by nuzrub** [lessw2020/Ranger-Deep-Learning-Optimizer#27]
I want to cite ranger on a Medium article and I would like to know if there is an arXiv publication of Ranger or a published peer-reviewed paper on some conference or journal.

I saw you linked a paper o the README.md, but it does not seem to be about ranger, as the very word does not appear in any part of it. I know the Radam and Lookahead paper, but the Ranger one is missing on my library. Thanks

**Comment by lessw2020** [comment]
Hi @nuzrub - thanks for checking.  There's no published paper on Ranger at this point, just the medium article where I introduced it:  https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d
Most papers have just cited the medium article.
I keep thinking soon we'll have an automated optimizer that does auto learning rate so never pushed towards a paper :) but looks like that time is still further out. 
Good luck with your article and feel free to post a link here. 
Hope you are doing well!

**Comment by nuzrub** [comment]
Thanks for replying. I do believe you should take sometime to write about Ranger, as I believe it is a great idea. In today's arXiv world, publishing ideas to the scientific community does not need to be as time consuming was it used to be with just journals and conferences. 
Auto learning rate is something I believe would be great to all. However, I also believe there will always be some other parameter at the optimizer level. If we find a way to automatically search a good learning rate, there is going to be another parameter to control how fast this automatic detection should adapt. We are all slaves to hyper parameters in the end :x
Thanks for replying, I will let you know when I publish my article o/
