### ISSUE TITLE
How to use ranger in keras? Please help me.

### ISSUE THREAD

**Issue by Kalisa1123** [lessw2020/Ranger-Deep-Learning-Optimizer#41]
Your optimizer looks like a big achievement！
I have used " optimizer=Ranger(lr=0.001)" in keras .
But I have a error named "TypeError: __init__() missing 1 required positional argument: 'params'".
I don't know how to debug it . Can you help me？

**Comment by lessw2020** [comment]
Hi @Kalisa1123  - the Ranger code here is for PyTorch and won't work when dropped into Keras.
There are Ranger implementations for Keras and TF:
1 - TF - https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/RectifiedAdam
2 - Keras specific:  https://github.com/CyberZHG/keras-lookahead  
`from keras_radam import RAdam
from keras_lookahead import Lookahead

optimizer = Lookahead(RAdam())
`
will give you a Ranger equivalent though it won't have GC (gradient centralization). 
Hope that helps!
