### ISSUE TITLE
best result : flat learning rate for 75%      it means ranger optimizer is not sensitive to lr?

### ISSUE THREAD

**Issue by progressforever** [lessw2020/Ranger-Deep-Learning-Optimizer#45]
Thank you for your excellent work~
I notice that the best model of ranger optimizer have flat learning rate for 75%.  Is it mean ranger optimizer is not sensitive to lr?

Looking forward to your early reply~

**Comment by lessw2020** [comment]
Hi @progressforever  - Ranger is still sensitive to learning rate.  The reason for the 75% at a flat learning rate is to let it explore the larger loss surface and ideally begin to hover around the widest basin.  
The drop then lets it go down into the basin and finalize (ideally) on the best generalization minima. 
Hope that helps!
