### ISSUE TITLE
N_sma_threshhold

### ISSUE THREAD

**Issue by kayuksel** [lessw2020/Ranger-Deep-Learning-Optimizer#6]
You first have 
`if N_sma > self.N_sma_threshhold:`

and then you have
`if N_sma > 4:`

Is it right that the second one is constant or should that also be N_sma_threshhold parameter?

**Comment by lessw2020** [comment]
Hi Kayuksel,
It was an oversight on my part - thanks for pointing it out!
I've fixed and checked it in.
Have a good weekend!
