### ISSUE TITLE
N_sma_threshhold should be instance variable

### ISSUE THREAD

**Issue by ohmorimori** [lessw2020/Ranger-Deep-Learning-Optimizer#7]
Thank you for the great implementation.
I think I found a small part to modify at ranger.py line 116.

original code:
if N_sma > N_sma_threshhold:

to be left:
if N_sma > self.N_sma_threshhold:

**Comment by lessw2020** [comment]
Hi @ohmorimori  - you are correct, ,thanks for pointing this out.
That is my mistake for not running the code, I just fixed in here directly b/c it was "so simple". 
I'm running the correction now and will check it in.

**Comment by lessw2020** [comment]
Fixed - thanks again!
